POST http://localhost:8080/events
Content-Type: application/json

 {
     "name": "Sample Event",
  "description": "This is a description of the sample event.",
  "location": "Sample Location",
   "datetime": "2024-08-12T12:00:00Z",
  "user_id": 26
  
  }